using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class GameWords {

    public string[] gameWords { get; set; }

    public GameWords()
    {
        gameWords = new string[90]{
            "gas pedal",
            "illusion",
            "pavement",
            "forecast",
            "choose",
            "straight",
            "complain",
            "recycle",
            "departure",
            "export",
            "test",
            "impound",
            "tell",
            "spell",
            "treatment",
            "deport",
            "slow",
            "split",
            "compound",
            "stop",
            "romantic",
            "simplicity",
            "litigation",
            "chimpanzee",
            "hook",
            "year",
            "list",
            "testify",
            "substitute",
            "faint",
            "hand",
            "hell",
            "rocket",
            "design",
            "cooperate",
            "tolerant",
            "rare",
            "wing",
            "rotation",
            "scan",
            "tune",
            "fork",
            "negotiation",
            "capture",
            "ruin",
            "fibre",
            "name",
            "tape",
            "relevance",
            "hear",
            "art",
            "mourning",
            "insert",
            "gossip",
            "blonde",
            "projection",
            "dentist",
            "drink",
            "stake",
            "decide",
            "helicopter",
            "cattle",
            "favour",
            "refrigerator",
            "capital",
            "factor",
            "map",
            "pest",
            "reliance",
            "feeling",
            "gear",
            "birthday",
            "morning",
            "assembly",
            "node",
            "candle",
            "lead",
            "prefer",
            "tumble",
            "fail",
            "innovation",
            "revenge",
            "thirsty",
            "nuance",
            "mirror",
            "pray",
            "benefit",
            "crackpot",
            "mutter",
            "shiver"
        };
    }
}
